SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 1000
SCREEN_MARGIN = 20
SCREEN_WITH_RANGE = int(SCREEN_WIDTH/2) - SCREEN_MARGIN
SCREEN_HEIGHT_RANGE = int(SCREEN_HEIGHT/2) - SCREEN_MARGIN
SEGMENT_COLLISION_MARGIN = 10

STARTING_POSITIONS = [(0, 0), (-20, 0), (-40, 0)]
SNAKE_COLOR = "white"
SNAKE_UP = 90
SNAKE_DOWN = 270
SNAKE_LEFT = 180
SNAKE_RIGHT = 0
SNAKE_MOVE = 20

FOOD_COLOR = "purple"
FOOD_COLLISION_MARGIN = 15
FOOD_STRETCH_WIDTH = 0.5
FOOD_STRETCH_LENGTH = 0.5

SCORE_COLOR = "white"
SCORE_FONT = "Arial"
SCORE_FONT_SIZE = 12
SCORE_FONT_TYPE = "normal"
SCORE_ALIGN = "center"
