SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_MARGIN = 20
SCREEN_COLOR = "black"
SCREEN_TITLE = "My Pong"
SCREEN_WITH_RANGE = int(SCREEN_WIDTH/2) - SCREEN_MARGIN
SCREEN_HEIGHT_RANGE = int(SCREEN_HEIGHT/2) - SCREEN_MARGIN

PADDLE_COLOR = "white"
PADDLE_STRETCH_WIDTH = 5
PADDLE_STRETCH_LENGTH = 1
PADDLE_UP = 90
PADDLE_DOWN = 270
PADDLE_LEFT = 180
PADDLE_RIGHT = 0
PADDLE_MOVE = 20

BALL_COLOR = "white"
BALL_WIDTH = 20
BALL_HEIGHT = 20
BALL_STRETCH_WIDTH = 1
BALL_STRETCH_LENGTH = 1
BALL_MOVE = 10

SCORE_COLOR = "white"
SCORE_FONT = "Courier"
SCORE_SIZE = 40
SCORE_ALIGN = "center"
