SCREEN_COLOR = "black"
SCREEN_TITLE = "My Turtle Crossing"
SCREEN_WIDTH = 600
SCREEN_HEIGHT = 600
SCREEN_MARGIN = 20
SCREEN_WITH_RANGE = int(SCREEN_WIDTH/2) - SCREEN_MARGIN
SCREEN_HEIGHT_RANGE = int(SCREEN_HEIGHT/2) - SCREEN_MARGIN

SCORE_COLOR = "black"
SCORE_FONT = "Courier"
SCORE_FONT_SIZE = 24
SCORE_SIZE = 12
SCORE_ALIGN = "left"
SCORE_X_POS = -SCREEN_WITH_RANGE
SCORE_Y_POS = SCREEN_HEIGHT_RANGE - SCREEN_MARGIN

PLAYER_COLOR = "black"
PLAYER_POSITION = (0, -SCREEN_HEIGHT_RANGE)
PLAYER_MOVE = 10
FINISH_LINE_Y = SCREEN_HEIGHT_RANGE

CAR_COLORS = ["red", "orange", "yellow", "green", "blue", "purple"]
CAR_STARTING_MOVE_DISTANCE = 5
CAR_MOVE_INCREMENT = 10
CAR_Y_RANGE =  int(SCREEN_HEIGHT/2) - 50

